---
title: "gdm_plants"
date: "08/06/2021"
output: html_notebook
---

## Tidy biological data ##

# Plants #

```{r}

npms_spp <- readRDS("data/plants/prep_data/npms_spp_yr.rds")
# length(unique(npms_spp$species)) = 1071 species
# length(unique(npms_spp$monad)) = 457 sites

npms_foc <- npms_spp %>%  
  # all years = focal years
  dplyr::rename(site = monad) %>% 
  dplyr::mutate(year = as.integer(year)) %>% 
  # cell identifier
  dplyr::mutate(cell = paste0(x, y))

# locations
npms_xy <- dplyr::distinct(npms_foc, site, x, y, cell)

# summarise data across years
npms_comb <- npms_foc %>% 
  # per site and species
  dplyr::group_by(cell, species, x, y) %>% 
  # summarise presence across years per site and species
  dplyr::summarise(sind = max(sind)) %>% 
  dplyr::ungroup()

```

## Sample coverage ##

```{r}

# prepare data into split list for each site speciesxyear matrix
npms_split <- npms_foc %>% 
  dplyr::select(cell, species, year, sind) %>%
  # add year_ to year column to make easier column names
  dplyr::mutate(year = paste0("year_", year)) %>% 
  # complete data with zeros for species per site per sampled year
  tidyr::complete(tidyr::nesting(cell, year), species, fill = list(sind = 0)) %>% 
  # convert to wide format - each year is a sample
  tidyr::pivot_wider(names_from = year, values_from = sind) %>% 
  # split into a list
  split(., .$cell) 

# convert to format for iNEXT function
npms_inxt <- lapply(npms_split, function(x) {
  
  x %>% 
    # drop cell identifier
    dplyr::select(-cell) %>% 
    # drop unsampled years
    janitor::remove_empty(which = "cols") %>% 
    # add species as rownames
    tibble::column_to_rownames("species") %>% 
    # convert to matrix
    as.matrix(.)
  
    })

# # calculate sample coverage
# inxt <- lapply(1:length(npms_inxt), function(x) {
#   
#   # run inext but catch errors and return NULL
#   return(tryCatch(iNEXT::iNEXT(npms_inxt[x], datatype = "incidence_raw"), error = function(e) NULL))
#   
# })
# 
# saveRDS(inxt, "data/plants/out_data/npms_inxt.rds")

inxt <- readRDS("data/plants/out_data/npms_inxt.rds")

# # extract sample coverage estimates data frame
# # get dataframe from inext objects
# inxt_df <- sapply(inxt, "[[", 1) %>% 
#   # combine
#   dplyr::bind_rows() %>% 
#   # remove broken site column
#   dplyr::select(-site) %>% 
#   # add cell identifier
#   tibble::rownames_to_column("cell") %>%
#   # sites with at least two sampled years
#   dplyr::filter(T > 1) %>% 
#   # sites with at least two sampled species
#   dplyr::filter(S.obs > 1)
# 
# # save sample coverage dataframe for plot in gdm_cross_taxa.Rmd
# saveRDS(inxt_df, "data/plants/out_data/plants_inxt_df.rds")

inxt_df <- readRDS("data/plants/out_data/plants_inxt_df.rds")

```

## Tidy plant data based on environmental data ##

```{r}

# identify cells lacking environmental data

# prepare raster data with cell coordinates
env_dat <- as.data.frame(covars, xy = TRUE)

# identify raster cells per site
cellID <- as.data.frame(terra::cellFromXY(covars, as.matrix(dplyr::select(npms_xy, x, y)))) %>%
  setNames("cell_id")

cell_info <- dplyr::bind_cols(cellID, npms_xy)

# join biological locations to environmental data
npms_env <- dplyr::left_join(npms_xy, env_dat, by = c("x", "y")) %>% 
  # drop cells with missing env data
  dplyr::filter(!is.na(tri))

# remove cells with missing env data from biological data
npms <- npms_comb %>% 
  # remove cells with missing env data from biological data
  dplyr::filter(cell %in% npms_env$cell) %>% 
  # join sample coverage data
  dplyr::left_join(inxt_df, by = "cell") %>% 
  # filter out sites with no sample coverage estimate
  dplyr::filter(!is.na(SC)) %>% 
  # add cell information (x, y)
  dplyr::left_join(cell_info, by = c("cell", "x", "y"))

# # save: npms
# saveRDS(npms, "data/plants/out_data/npms.rds")

```

## GDM analysis ##

```{r}

# GDM

# weights based on sample coverage
weig <- dplyr::select(npms, cell_id, weights = SC) %>% 
  dplyr::distinct(cell_id, .keep_all = TRUE)

# format site pair for gdm
# weighted by sample coverage
gdmTab <- gdm::formatsitepair(npms, bioFormat = 2, dist = "jaccard", XColumn = "x", YColumn = "y", abundance = FALSE, sppColumn = "species", siteColumn = "cell_id", predData = raster::stack(covars), weightType = "custom", custWeights = weig, verbose = TRUE)
# Site-pair table created with 31878 rows (253 unique sites) and 26 columns (10 environmental variables)

saveRDS(gdmTab, "data/plants/out_data/plants_gdmTab.rds")

# run gdm
gdmr <- gdm::gdm(gdmTab, geo = TRUE)

# summary(gdmr)
# 
# plot(gdmr)

# save model
saveRDS(gdmr, "data/plants/out_data/plants_gdmr.rds")

```

