---
title: "gdm_butterflies"
author: "Rob Cooke"
date: "08/06/2021"
output: html_notebook
---
# Butterflies #

## Tidy biological data ##

```{r}

bms_spp <- readRDS("data/butterflies/prep_data/bms_spp_yr.rds")

bms_xy <- readRDS("data/butterflies/prep_data/bms_xy.rds")

# length(unique(bms_spp$species)) = 57 species

bms_foc <- bms_spp %>%  
  # focal years - last 10 years of baseline period, as realization of community
  dplyr::filter(year %in% 2001:2010)

# incidence
bms_pa <- bms_foc %>% 
  # convert to presence-absence
  dplyr::mutate(sind = ifelse(sind > 0, 1, 0))

# summarise data across years
bms_comb <- bms_pa %>% 
  # per cell and species
  dplyr::group_by(x_cell, y_cell, cell, species) %>% 
  # summarise presence across years per cell and species
  dplyr::summarise(sind = max(sind)) %>% 
  dplyr::ungroup()

```

## Sample coverage ##

```{r}

# # prepare data into split list for each site speciesxyear matrix
# bms_split <- bms_pa %>% 
#   dplyr::select(cell, species, year, sind) %>%
#   # add year_ to year column to make easier column names
#   dplyr::mutate(year = paste0("year_", year)) %>% 
#   # complete data with zeros for species per site per sampled year
#   tidyr::complete(tidyr::nesting(cell, year), species, fill = list(sind = 0)) %>% 
#   # convert to wide format - each year is a sample
#   tidyr::pivot_wider(names_from = year, values_from = sind) %>% 
#   # split into a list
#   split(., .$cell) 
# 
# # convert to format for iNEXT function
# bms_inxt <- lapply(bms_split, function(x) {
#   
#   x %>% 
#     # drop cell identifier
#     dplyr::select(-cell) %>% 
#     # drop unsampled years
#     janitor::remove_empty(which = "cols") %>% 
#     # add species as rownames
#     tibble::column_to_rownames("species") %>% 
#     # convert to matrix
#     as.matrix(.)
#   
#     })
# 
# # calculate sample coverage
# inxt <- lapply(1:length(bms_inxt), function(x) {
# 
#   # run inext but catch errors and return NULL
#   return(tryCatch(iNEXT::iNEXT(bms_inxt[x], datatype = "incidence_raw"), error = function(e) NULL))
# 
# })
# 
# # extract sample coverage estimates data frame
# # get dataframe from inext objects
# inxt_df <- sapply(inxt, "[[", 1) %>%
#   # combine
#   dplyr::bind_rows() %>%
#   # remove broken site column
#   dplyr::select(-site) %>%
#   # add proper site column
#   tibble::rownames_to_column("site") %>%
#   # sites with at least two sampled years
#   dplyr::filter(T > 1) %>%
#   # sites with at least two sampled species
#   dplyr::filter(S.obs > 1)
# 
# # save sample coverage dataframe for plot in gdm_cross_taxa.Rmd
# saveRDS(inxt_df, "data/butterflies/out_data/butterflies_inxt_df.rds")

inxt_df <- readRDS("data/butterflies/out_data/butterflies_inxt_df.rds")

```

## Tidy butterfly data based on environmental data ##

```{r}

# identify cells lacking environmental data

# prepare raster data with cell coordinates
env_dat <- as.data.frame(covars, xy = TRUE)

# identify raster cells per site
cellID <- as.data.frame(terra::cellFromXY(covars, as.matrix(sf::st_set_geometry(dplyr::select(bms_xy, X, Y), NULL)))) %>%
  setNames("cell_id")

# get x,y coordinates for each cell
cellLocs <- as.data.frame(terra::xyFromCell(covars, cellID$cell_id)) %>% 
  # add bms transect information
  dplyr::bind_cols(bms_xy) %>% 
  # rename to prevent confusion with transect X and Y
  dplyr::rename(x_cell = x, y_cell = y) %>% 
  dplyr::select(site, x_cell, y_cell)

# join biological cell locations to environmental data
bms_env <- dplyr::left_join(cellLocs, env_dat, by = c("x_cell" = "x", "y_cell" = "y")) %>% 
  # drop cells with missing env data
  dplyr::filter(!is.na(tri)) %>% 
  # create cell identifier
  dplyr::mutate(cell = paste0(x_cell, y_cell))

cell_info <- dplyr::bind_cols(cellID, cellLocs)

# remove cells with missing env data from biological data
bms <- dplyr::filter(bms_comb, cell %in% bms_env$cell) %>% 
  # join sample coverage data
  dplyr::left_join(inxt_df, by = c("cell" = "site")) %>% 
  # filter out sites with no sample coverage estimate
  dplyr::filter(!is.na(SC)) %>% 
  # filter to presences
  dplyr::filter(sind == 1) %>% 
  # add cell information (x, y)
  dplyr::left_join(cell_info, by = c("x_cell", "y_cell"))

# # save: bms
# saveRDS(bms, "data/butterflies/out_data/bms.rds")

```

## GDM analysis ##

```{r}

# GDM

# weights based on sample coverage
weig <- dplyr::select(bms, cell_id, weights = SC) %>% 
  dplyr::distinct(cell_id, .keep_all = TRUE)

# format site pair for gdm
# weighted by sample coverage
gdmTab <- gdm::formatsitepair(bms, bioFormat = 2, dist = "jaccard", XColumn = "x_cell", YColumn = "y_cell", abundance = FALSE, sppColumn = "species", siteColumn = "cell_id", predData = raster::stack(covars), weightType = "custom", custWeights = weig, verbose = TRUE)
# Site-pair table created with 428275 rows (926 unique sites) and 26 columns (10 environmental variable)

saveRDS(gdmTab, "data/butterflies/out_data/butterflies_gdmTab.rds")

# run gdm
gdmr <- gdm::gdm(gdmTab, geo = TRUE)

# summary(gdmr)
# 
# plot(gdmr)

# save model
saveRDS(gdmr, "data/butterflies/out_data/butterflies_gdmr.rds")

```
